allowBuilds:
  '@firebase/util': true
  '@vaadin/vaadin-usage-statistics': true
  esbuild: true
  protobufjs: true
  re2: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@vaadin/vaadin-usage-statistics'
onlyBuiltDependencies:
  - esbuild
  - protobufjs
packages:
  - scripts
